import java.util.ArrayList;
import java.util.List;

public class FlightDataConstants {
    public static String YEAR = "Year";
    public static String QUARTER = "Quarter";
    public static String MONTH = "Month";
    public static String DAY_OF_MONTH = "DayOfMonth";
    public static String DAY_OF_WEEK = "DayOfWeek";
    public static String FLIGHT_DATE = "FlightDate";
    public static String UNIQUE_CARRIER = "UniqueCarrier";
    public static String AIRLINE_ID = "AirlineID";
    public static String CARRIER = "Carrier";
    public static String TAIL_NUM = "TailNum";
    public static String FLIGHT_NUM = "FlightNum";
    public static String ORIGIN = "Origin";
    public static String ORIGIN_CITY_NAME = "OriginCityName";
    public static String ORIGIN_STATE = "OriginState";
    public static String ORIGIN_STATE_FIPS = "OriginStateFips";
    public static String ORIGIN_STATE_NAME = "OriginStateName";
    public static String ORIGIN_WAC = "OriginWac";
    public static String DEST = "Dest";
    public static String DEST_CITY_NAME = "DestCityName";
    public static String DEST_STATE = "DestState";
    public static String DEST_STATE_FIPS = "DestStateFips";
    public static String DEST_STATE_NAME = "DestStateName";
    public static String DEST_WAC = "DestWac";
    public static String CRS_DEP_TIME = "CRSDepTime";
    public static String DEP_TIME = "DepTime";
    public static String DEP_DELAY = "DepDelay";
    public static String DEP_DELAY_MINUTES = "DepDelayMinutes";
    public static String DEP_DEL_15 = "DepDel15";
    public static String DEPARTURE_DELAY_GROUPS = "DepartureDelayGroups";
    public static String DEP_TIME_BLK = "DepTimeBlk";
    public static String TAXI_OUT = "TaxiOut";
    public static String WHEELS_OFF = "WheelsOff";
    public static String WHEELS_ON = "WheelsOn";
    public static String TAXI_IN = "TaxiIn";
    public static String CRS_ARR_TIME = "CRSArrTime";
    public static String ARR_TIME = "ArrTime";
    public static String ARR_DELAY = "ArrDelay";
    public static String ARR_DELAY_MINUTES = "ArrDelayMinutes";
    public static String ARR_DEL_15 = "ArrDel15";
    public static String ARRIVAL_DELAY_GROUPS = "ArrivalDelayGroups";
    public static String ARR_TIME_BLK = "ArrTimeBlk";
    public static String CANCELLED = "Cancelled";
    public static String CANCELLATION_CODE = "CancellationCode";
    public static String DIVERTED = "Diverted";
    public static String CRS_ELAPSED_TIME = "CRSElapsedTime";
    public static String ACTUAL_ELAPSED_TIME = "ActualElapsedTime";
    public static String AIR_TIME = "AirTime";
    public static String FLIGHTS = "Flights";
    public static String DISTANCE = "Distance";
    public static String DISTANCE_GROUP = "DistanceGroup";
    public static String CARRIER_DELAY = "CarrierDelay";
    public static String WEATHER_DELAY = "WeatherDelay";
    public static String NAS_DELAY = "NASDelay";
    public static String SECURITY_DELAY = "SecurityDelay";
    public static String LATE_AIRCRAFT_DELAY = "LateAircraftDelay";
    public static List<String> COLUMN_QUALIFIERS = new ArrayList<String>(){
        {
            add(YEAR);
            add(QUARTER);
            add(MONTH);
            add(DAY_OF_MONTH);
            add(DAY_OF_WEEK);
            add(FLIGHT_DATE);
            add(UNIQUE_CARRIER);
            add(AIRLINE_ID);
            add(CARRIER);
            add(TAIL_NUM);
            add(FLIGHT_NUM);
            add(ORIGIN);
            add(ORIGIN_CITY_NAME);
            add(ORIGIN_STATE);
            add(ORIGIN_STATE_FIPS);
            add(ORIGIN_STATE_NAME);
            add(ORIGIN_WAC);
            add(DEST);
            add(DEST_CITY_NAME);
            add(DEST_STATE);
            add(DEST_STATE_FIPS);
            add(DEST_STATE_NAME);
            add(DEST_WAC);
            add(CRS_DEP_TIME);
            add(DEP_TIME);
            add(DEP_DELAY);
            add(DEP_DELAY_MINUTES);
            add(DEP_DEL_15);
            add(DEPARTURE_DELAY_GROUPS);
            add(DEP_TIME_BLK);
            add(TAXI_OUT);
            add(WHEELS_OFF);
            add(WHEELS_ON);
            add(TAXI_IN);
            add(CRS_ARR_TIME);
            add(ARR_TIME);
            add(ARR_DELAY);
            add(ARR_DELAY_MINUTES);
            add(ARR_DEL_15);
            add(ARRIVAL_DELAY_GROUPS);
            add(ARR_TIME_BLK);
            add(CANCELLED);
            add(CANCELLATION_CODE);
            add(DIVERTED);
            add(CRS_ELAPSED_TIME);
            add(ACTUAL_ELAPSED_TIME);
            add(AIR_TIME);
            add(FLIGHTS);
            add(DISTANCE);
            add(DISTANCE_GROUP);
            add(CARRIER_DELAY);
            add(WEATHER_DELAY);
            add(NAS_DELAY);
            add(SECURITY_DELAY);
            add(LATE_AIRCRAFT_DELAY);
        }
    };
    public static String TABLE_NAME = "Flights";
    public static String COL_FAMILY = "FLIGHT_INFO";
};
